### ISSUE TITLE
Wählhilfe bei FW 7.11

### ISSUE THREAD

**Issue by Goldbacher** [jfritz-org/jfritz#13]
Hallo, was muss ich einstellen, damit die Wählhilfe wieder funktionier?

**Comment by simulachaos** [comment]
Hi, ich habe ein identisches Problem mit jFritz seit das Fritz OS auf 7.11 upgedated worden ist. Kann sich einer derEntwickler das Problem bitte mal anschauen- wäre schade wenn jFritz nicht mehr nutzbar wäre. Es scheint mit geändertem Telefonhandling in der Fritzbox zusammen zu hängen. Fallback beim Fritz OS scheidet wegen der neuen Funktionalität aus.

**Comment by jfritz-org** [comment]
Mit Version 0.7.7 behoben.
