### ISSUE TITLE
Wrong software-name in License

### ISSUE THREAD

**Issue by alexgit2k** [jfritz-org/jfritz#18]
License says Kodi but not jFritz: https://github.com/jfritz-org/jfritz/blob/master/LICENSE.GPL#L2
> You may use, distribute and copy **Kodi** under the terms of GNU General

**Comment by robotniko** [comment]
Thanks, fixed in master branch.

**Comment by alexgit2k** [comment]
Commit 5d48ffe9c98b56f8c8d9938871bb392b741b7f50
