### ISSUE TITLE
FritzBox Telefon Code 27.11.2017

### ISSUE THREAD

**Issue by mypikachu2** [jfritz-org/jfritz#5]
Hallo, ich weiß nicht ob du das schon gelesen hast aber vielleicht kannst du es in der nächsten Version Berücksichtigen, Danke.

Hier: https://github.com/mypikachu2/jfritz/commit/df022c05dcfdaa9f8a7ccc9a7f425baef0c83d96

**Comment by robotniko** [comment]
Hi, sieht auf den ersten Blick gut aus.  Kannst du dafür bitte einen Pull-Request erstellen, dann kann ich das leichter mergen.

**Comment by robotniko** [comment]
Ich habe das etwas angepasst und Tests dafür geschrieben, siehe commit https://github.com/jfritz-org/jfritz/commit/56c73b34d825989fb2565162ad66615a9a362b1a
