### ISSUE TITLE
Wählhilfe bei FBox 7412 fehlerhaft

### ISSUE THREAD

**Issue by arbor95** [jfritz-org/jfritz#7]
Die Wählhilfe zeigt bei mir (Fritzbox 7412) 3 Einträge zum Heraustelefonieren. 
der erste Fehler:
Es gibt eigentlich nur 2 Möglichkeiten: Privat (Dect) und Büro (Fon1). Es wird noch ISDN angezeigt (die 7412 hat keines)
aber der zweite (Gravierende) Fehler:
Es wird, egal welchen der 3 Einträge ich nehme, immer mit dem unter Privat definierten Eintrag herausgerufen (d.h. wenn ich mit Büro herausrufen will klingelt das "falsche" Telefon (Privat) bei Verbindung und die Nummer mit der Herausgerufen wird ist die Privat)

**Comment by mypikachu** [comment]
Das könnte das Problem hier sein: Ausführung bestimmter Einstellungen und Funktionen zusätzlich bestätigen ->  https://www.ip-phone-forum.de/threads/jfritz-einschr%C3%A4nkung-nach-fritzbox-update.297242/page-2#post-2249962

**Comment by arbor95** [comment]
Vermutlich muss ich richtig lesen lernen: ISDN oder Dect.
Es sind zwar keine weitern Dect Geräte definiert, aber wenn eines defniert wäre ...
